### ISSUE TITLE
Trying to add line numbers to ocg, to make them toggleable

### ISSUE THREAD

**Issue by hope965** [latex-lineno/lineno#1]
Hey there I am currently facing the problem that I need to have line numbers which can be turned on or off via the ocg of PDFs.

I tried to add the ocgx2 package around the line numbers but I struggle to find the correct location on where to do so.

Could you point me into the right direction where to look in the sty file. (where the actual line number is printed)

**Comment by kwwette** [comment]
@hope965 Afraid I can't be of much help. I've only recently been asked to take over maintenance of this package, and I don't yet understand the code to that level.
