### ISSUE TITLE
Compatibility with balance

### ISSUE THREAD

**Issue by koppor** [latex-lineno/lineno#2]
I have issues in using [pbalance](https://gitlab.com/lago/pbalance) together with lineno:

```latex
\documentclass[twocolumn]{article}
\usepackage{mwe}
\usepackage{lineno}
\usepackage{pbalance}
\begin{document}
\lipsum[1-13]
\end{document}
```

Result:

![grafik](https://user-images.githubusercontent.com/1366654/174503077-d507f0b9-afb7-493b-a10e-d5494bebbb04.png)

The author of pbalance (@urrameu) states: 

> Unfortunately, fixing this goes WAY beyond my TeX knowledge.

Source: https://gitlab.com/lago/pbalance/-/issues/2#note_996277132

Maybe, @kwwette could support him?

**Comment by kwwette** [comment]
Sorry @koppor but I also don't have the TeX knowledge (or time) to debug this.

You might want to look at the `revtex` class used in physics. It supports line numbers, and can also balance columns. It may be suitable for your needs.

**Comment by urrameu** [comment]
Hi,

I am the author of pbalance. I figured out a way to solve this problem, but have not yet implemented it (I will in the next couple of days). Still, I will check revtex too.
